# Generated by Django 2.1.4 on 2018-12-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('client_company', models.CharField(max_length=150)),
                ('company_location', models.CharField(max_length=50)),
                ('company_logo', models.ImageField(default='media/None/no-image.png', upload_to='media/pic_folder/')),
                ('contactno', models.CharField(max_length=20)),
                ('project_name', models.CharField(max_length=100)),
                ('tools', models.CharField(max_length=100)),
                ('offer_date', models.CharField(max_length=150)),
                ('deadline', models.CharField(max_length=150)),
            ],
        ),
    ]
