# Generated by Django 2.1.4 on 2018-12-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20181230_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientlist',
            name='company_logo',
            field=models.ImageField(blank=True, default='media/no-image.png', null=True, upload_to='img/'),
        ),
    ]
